### ISSUE TITLE
Does ghcjs-hello have to be so complicated?

### ISSUE THREAD

**Issue by erikkaplun** [ghcjs/ghcjs-examples#12]
I was hoping for a simple Hello World that runs inside Webkit when natively compiled, or compiles to a simple JS application. But it seems to rely on stuff like Sodium even.

**Comment by hamishmack** [comment]
Yeah it is more of a test bed & demo than a hello world.  Check out [ghcjs-dom-hello](https://github.com/ghcjs/ghcjs-dom-hello) instead.

**Comment by erikkaplun** [comment]
Thank you!
